export default {
  INIT_LOGIN: 'INIT_LOGIN',
  SUCCEED_LOGIN: 'SUCCEED_LOGIN',
  INIT_LOGOUT: 'INIT_LOGOUT',
  SUCCEED_LOGOUT: 'SUCCEED_LOGOUT',
  RUN_CODE: 'RUN_CODE',
  SHOW_RESULTS: 'SHOW_RESULTS',
  RESET_RESULTS: 'RESET_RESULTS',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION'
}
