export default {
  INIT_LOGIN: 'INIT_LOGIN',
  SUCCEED_LOGIN: 'SUCCEED_LOGIN',
  INIT_LOGOUT: 'INIT_LOGOUT',
  SUCCEED_LOGOUT: 'SUCCEED_LOGOUT',
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION'
}
